### ISSUE TITLE
Difference in behavior with jq

### ISSUE THREAD

**Issue by AdamantGarth** [itchyny/gojq#175] opened 2022-05-19 15:16 UTC
The following jq script (scary, I know):
```jq
def render($parents):
	.[] | .data as [$id, $props, $children] | $props |
	if has("label") then
		(.label.data | gsub("_(?<u>_?)"; "\(.u)")) as $label |
		if .visible.data == false then
			empty
		elif .enabled.data == false then
			"\t\u001b[90m\($parents)<\($label)>\u001b[0m"
		elif ."children-display".data == "submenu" then
			$children | render("\($parents)\u001b[90m\($label) > \u001b[0m")
		else
			(."toggle-state".data | if . == 0 then [" ","\u001b[91m"] elif . == 1 then ["x","\u001b[92m"] else ["~", "\u001b[93m"] end) as [$tstate, $tcolor] |
			(."toggle-type".data | if . == "checkmark" then "\($tcolor)[\($tstate)] " elif . == "radio" then "\($tcolor)(\($tstate)) " else "" end) as $toggle |
			"\($id)\t\($parents)\($toggle)\($label)\u001b[0m"
		end
	elif .type.data? == "separator" then
		"\t\($parents)\u001b[90m----------\u001b[0m"
	else
		empty
	end
;
.data[1][2] | render("")
```
Works great in gojq, but fails in jq (both release and master) with the following error:
```
jq: error: syntax error, unexpected label, expecting IDENT (Unix shell quoting issues?) at <top-level>, line 4:
                (.label.data | gsub("_(?<u>_?)"; "\(.u)")) as $label |
jq: error: Possibly unterminated 'if' statement at <top-level>, line 3:
        if has("label") then
jq: 2 compile errors
```

I primarily use gojq, so didn't notice the error when I wrote the script, and now I'm not really sure what it means and where to look. Not a huge deal for me, it's great that it works in gojq (thanks a lot for it, btw). Not that I'd like it to get 'fixed', though - just thought I'd report the difference in behavior so you can put it in the README or something.

**Comment by wader** [comment] 2022-05-19 15:28
Minimized it to:
```sh
$ jq -n 'if true then . as $label | . end'
jq: error: syntax error, unexpected label, expecting IDENT (Unix shell quoting issues?) at <top-level>, line 1:
if true then . as $label | . end
jq: error: Possibly unterminated 'if' statement at <top-level>, line 1:
if true then . as $label | . end
jq: 2 compile errors
```
or maybe even more:
```sh
$ jq -n '. as $label | .'
jq: error: syntax error, unexpected label, expecting IDENT (Unix shell quoting issues?) at <top-level>, line 1:
. as $label | .
jq: 1 compile error
```
work fine with renamed binding

`label` is reserved keyword in jq but not gojq?

**Comment by itchyny** [comment] 2022-05-19 23:21
This is working as intended so closing. The README.md already mentions about using keywords for variable names. `label` is also reserved in gojq but keyword tokens and variables are considered different in gojq lever. On the other hand jq does not have variable token in its lexer so parses two tokens `$` and identifier as variable name. That's why `. as $ a | $ a` works in jq but not in gojq, `. as $if | $if` works in gojq but not in jq.

**Closed by itchyny** 2022-05-19 23:21 UTC
