### ISSUE TITLE
gojq: compile error: variable not defined: $ARGS (while reading ~/.jq)

### ISSUE THREAD

**Issue by systemmonkey42** [itchyny/gojq#231] opened 2023-12-06 23:33 UTC
GOJQ doesn't support `$<variables>` while reading the `~/.jq` file.

I built gojq based on HEAD (279485b121df) and immediately got the following error
```
go run ./cmd/gojq -n '.'
gojq: compile error: variable not defined: $ARGS
```
It turns out I have macros in `~/.jq` which use various `$<variables>` including `$ARGS.named` 
and `gojq` fails with `variable not defined` while loading.

This is a symptom of a larger problem with variables (and scoping) in general.

For example, the following produce different results because of the order and scope of variable definition/expansion
```
$ echo \"hello\" | jq --arg value first 'def v: $value//"<empty>"; "none" as $value| v'
"first"
$ echo \"hello\" | go run ./cmd/gojq --arg value first 'def v: $value//"<empty>"; "none" as $value| v'
"none"
```

It seems `jq` doesn't produce an error when macros are defined, but maintains the original (semantic) scope when the macro is used.

The following shows `gojq` fails the macro definition because the variable does not exists.  `jq` won't fail unless you actually use the macro.
```
$ echo \"hello\" | jq 'def v: $value//"<empty>"; "none" as $value | .'
"hello"
$ echo \"hello\" | go run ./cmd/gojq 'def v: $value//"<empty>"; "none" as $value | .'
gojq: compile error: variable not defined: $value
exit status 3
```

Thanks

**Comment by itchyny** [comment] 2024-01-01 04:45
1. As the issue title, the variable `$ARGS` is not available in `~/.jq`. This is caused by the order of compiling initial modules and pre-defined variables. I'll fix this issue soon.
2. A variable binding after a function declaration incorrectly refers to the same name binding before the function declaration. Although gojq has the same semantic scope (`gojq -n '"a" as $v | def f: $v; ("b" as $v | f)'` yields `"a"`), but when there is no parentheses like `"a" as $v | def f: $v; "b" as $v | f`, the two `$v` mistakenly refer to the same variable. I'll fix this issue soon.
3. Variable not defined error is emitted in unused function declarations. I'm not sure this should be fixed, because the function is incorrectly implemented. This is not the same issue of the issue 1 because `$ARGS` should be defined in the command context. In jq, users can define a function in `~/.jq` including variables they give by `--arg` to the command, but not sure how this is useful, and also have difficulty making this case work the same in gojq.

**Closed** 2024-01-01 04:48 UTC
