### ISSUE TITLE
"Command terminated abnormally."

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#85] opened 2021-07-10 05:13 UTC
The following program defines `partitions($n)` and has been tested quite extensively using both jq and gojq for small and medium values of $n.    

For `partitions(6666)`, the program (with tiny adaptations) runs successfully using jq with the BigInt.jq library, but with gojq, the only output is:

     Command terminated abnormally.

Further details about the program can be found at https://rosettacode.org/wiki/Partition_function_P#Recursive

```
def partitions($n):
  def div2: (. - (.%2)) / 2;
  reduce range(1; $n + 1) as $i ( {p: ([1] + [range(0;$n)|0])};
    . + {k: 0, stop: false}
    | until(.stop;
        .k += 1
        | (((.k * (3*.k - 1)) | div2) ) as $j
        | if $j > $i then .stop=true
  	else if (.k % 2) == 1
  	     then .p[$i] = .p[$i] + .p[$i - $j]
             else .p[$i] = .p[$i] - .p[$i - $j]
             end
          | (((.k * (3*.k + 1)) | div2)) as $j
  
          | if $j > $i then .stop=true
            elif (.k % 2) == 1
            then .p[$i] = .p[$i] + .p[$i - $j]
            else .p[$i] = .p[$i] - .p[$i - $j]
    	  end
  	end ))
    | .p[$n] ;
```

**Comment by itchyny** [comment] 2021-07-10 11:10
It runs successfully to calculate `partitions(7000)` on my machine, but with lots of memory. Do you expect gojq to run this program with constant memory?

**Comment by pkoppstein** [comment] 2021-07-10 13:29
It would be nice if the memory requirements were approx. linear in $n, especially if no more memory would be required than for jq.

It would also be helpful if a more specific failure message were printed when memory is exhausted. Thanks.

**Comment by itchyny** [comment] 2021-07-10 13:59
My understanding is the message is emitted by shell and the process is KILLed by OOM killer so there's no way we can handle this.

**Comment by itchyny** [comment] 2021-07-10 14:08
And this is not caused by lacking TCO. This is likely caused by the inefficiency that gojq cannot track the reference count of objects and arrays, unlike jq. The array is copied every time when `.p` is updated.

**Comment by wader** [comment] 2021-07-10 20:28
A bit related to this, it would be nice if gojq supported some kind of memory resource limits. But maybe tricky to limit in terms of  bytes? would a limit on env values size etc make sense?

**Comment by itchyny** [comment] 2021-07-11 00:25
I understand the performance issue but resolving it will cause many problem with custom functions. Closing due to not tackling for now.

**Closed by itchyny** 2021-07-11 00:25 UTC
