### ISSUE TITLE
"For paths starting with $ORIGIN/, the path of the jq executable is substituted for $ORIGIN."

### ISSUE THREAD

**Issue by pkoppstein** [itchyny/gojq#217] opened 2023-06-20 03:07 UTC
Regarding the "search" path specified e.g. in `include` directives, the jq manual states:

      For paths starting with $ORIGIN/, the path of the jq executable is substituted for $ORIGIN.

This does not seem to be currently supported by gojq, as evidenced by this transcript:
```
./jq  -n 'include "testme" {"search": "$ORIGIN/../../../jq"}; testme'
"Found"

./gojq -n 'include "testme" {"search": "$ORIGIN/../../../jq"}; testme'
gojq: compile error: module not found: "testme"
```

**Comment by itchyny** [comment] 2023-06-24 12:41
I admit the feature isn't implemented as pointed out, and fixing wouldn't be that difficult. However, I noticed that jq implementation is also broken about resolving `$ORIGIN` when the program was invoked by its name and looked up from `$PATH`. Also I'm always confused by the manual statement; `the path of the jq executable` is actually the directory where the executable is located in.

**Comment by pkoppstein** [comment] 2023-06-26 04:29
Although I agree that the expression "the path of the jq executable" is potentially fraught, in practice I don't have any problems with the way the current jq ("master") interprets $ORIGIN (namely, as the actual location of the executable).

For example, I have a jq executable at ~/github/jqMaster/jq and I have a symbolic link to it in ~/jq/, and a file ~/jq/testme.jq, and I have no problem with the `include "testme" {search:  _};` directive where _ is a suitable expression beginning with "$ORIGIN", whether I call jq using the symbolic link or its actual location.
```
$ grep include ORIGIN.jq
include "testme" {search: "$ORIGIN/../jq"};
$ ./link_to_jqMaster -n -f ORIGIN.jq
"Found"
### now adjust the "search:" value ...
$ grep include ORIGIN.jq
include "testme" {search: "$ORIGIN/../../jq"};
$ ~/github/jqMaster/jq -n -f ORIGIN.jq
"Found"
```

p.s. I realize that the existence of "hard links" makes the "the" in "the actual location" potentially somewhat problematic, but I'm sure you understand.

**Comment by itchyny** [comment] 2023-06-26 04:36
Does it work with `export PATH=~/github/jqMaster/:$PATH` and `jq -n -f ORIGIN.jq`?

**Comment by pkoppstein** [comment] 2023-06-26 05:14
I can get it to work using that export command, but there does seem to be a problem as I have to use the "wrong" value for "search". It seems that in this case, jq is mistranslating "$ORIGIN/" as "$ORIGIN/../" !

By the way, have you ever figured out how to use jq's `modulemeta` built-in?

**Comment by itchyny** [comment] 2023-06-26 06:33
The issue is tracked by https://github.com/jqlang/jq/issues/1312. Currently jq resolves the `argv[0]`, that is `jq` when invoked from one of `$PATH`, and its `dirname` is `.`, namely the current working directory. So, unless the command is invoked by absolute or relative path to the executable, `$ORIGIN` is the current directory.

**Comment by pkoppstein** [comment] 2023-06-26 08:57
Aha! So simple, and yet so useless.  Tx!

**Closed** 2023-11-12 01:55 UTC

**Comment by itchyny** [comment] 2023-11-12 01:57
I implemented this feature.
