### ISSUE TITLE
module not found

### ISSUE THREAD

**Issue by juvygreen** [itchyny/gojq#158] opened 2022-02-18 16:19 UTC
Hi,
Can you give us an example on how to use the -L for supplying a directory path of the module via the command line?
We have tried putting the module in different directory but still it always return an error:
`gojq: compile error: module not found: "cs"`

Here is the command we used:
`gojq -L="/directory_name" 'import "cs" as cs; .Table | {"date": .CreationDateTime | cs::isoToEpoch}' < input.json`

the cs.jq module is located in the /directory_name. But it throwing us module not found.

gojq version:
gojq 0.12.6 (rev: 886515f/go1.17.3)

Thank you

**Comment by itchyny** [comment] 2022-02-19 06:17
Thanks for reporting this issue. Try `-L "/directory_name"` and `-L"/directory_name"`. Using `=` is supported only for long options and this is working as same as jq command (`-L=/tmp` is regarded as `-L "=/tmp"`). This is how GNU commands recognize command line flags (see [this manual](https://www.gnu.org/software/tar/manual/html_section/Styles.html)).
However this behavior looks confusing actually, and also the help (`gojq -h | grep -- -L`) is wrong. Furthermore, gojq accepted `-L=/tmp` before v0.12.5, because [go-flags](https://github.com/jessevdk/go-flags) supports this behavior. So this is actually an unexpected breaking regression.
Since gojq has its own flag parser (to support positional flags) currently, allowing `=` for short string options (`-L`, `-f`) is easy and may not break existing usages (except for users of paths with leading `=`). Also, it is unlikely to introduce `-=` as a short option in the future. So I fixed the implementation to recognize `-L="/tmp"` as `-L "/tmp"`. This will be released in the next release.

**Closed** 2022-02-19 06:17 UTC
