### ISSUE TITLE
gohq won't compile with the latest golang:alpine on ARM64

### ISSUE THREAD

**Issue by atyutyunnik** [itchyny/gojq#206] opened 2023-02-10 22:19 UTC
Doing a build with the latest golang:
```
echo "FROM golang:alpine as build
RUN apk update
RUN apk upgrade
RUN apk add git
RUN apk add gettext
RUN apk add make
ENV VERSION=latest
ENV CGO_ENABLED=0
RUN go install github.com/itchyny/gojq/cmd/gojq@latest" | docker build --platform linux/arm64 --build-arg TARGETARCH=arm64  -f - .
```

Error output:
```
Step 9/9 : RUN go install github.com/itchyny/gojq/cmd/gojq@latest
 ---> [Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 8fc81e2070f9
go: downloading github.com/itchyny/gojq v0.12.11
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/itchyny/timefmt-go v0.1.5
go: downloading golang.org/x/sys v0.2.0
go: downloading github.com/rivo/uniseg v0.2.0
runtime: copying /usr/local/go/src/runtime/tls_arm64.h to /tmp/go-build1530567791/b010/tls_GOARCH.h: write /tmp/go-build1530567791/b010/tls_GOARCH.h: copy_file_range: function not implemented
```

**Comment by itchyny** [comment] 2023-02-11 00:01
Please share the minimal Dockerfile to reproduce the issue.

**Comment by itchyny** [comment] 2023-02-11 00:05
I cannot reproduce the problem. Can you prune the docker caches and retry again?
```sh
 $ echo "FROM golang:alpine as build
RUN apk update
RUN apk upgrade
RUN apk add git
RUN apk add gettext
RUN apk add make
ENV VERSION=latest
ENV CGO_ENABLED=0
RUN go install github.com/itchyny/gojq/cmd/gojq@latest" | docker build --platform linux/arm64 --build-arg TARGETARCH=arm64  -f - .
[+] Building 38.4s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                     0.0s
 => => transferring dockerfile: 248B                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/golang:alpine                                                                                         2.4s
 => [1/7] FROM docker.io/library/golang:alpine@sha256:5c73545fe3a6e4f16fe5aa4ffbe4dfafefbaefd26ccdfc8744635589fb04dbcc                                  21.2s
 => => resolve docker.io/library/golang:alpine@sha256:5c73545fe3a6e4f16fe5aa4ffbe4dfafefbaefd26ccdfc8744635589fb04dbcc                                   0.0s
 => => sha256:55522c79112429742fe76c795b9509c5cd1e8198e0caa2a1e355c0e60a719576 286.26kB / 286.26kB                                                       0.9s
 => => sha256:77c3719091df856c5f475ef1f915f5bdefae5a829c12d4ae75914e31c581935f 95.76MB / 95.76MB                                                        19.8s
 => => sha256:5c73545fe3a6e4f16fe5aa4ffbe4dfafefbaefd26ccdfc8744635589fb04dbcc 1.65kB / 1.65kB                                                           0.0s
 => => sha256:ab85132e2e5c2ef3d41552af4a20c45af92ca153daaa0c0138f2c14324077e9a 1.16kB / 1.16kB                                                           0.0s
 => => sha256:7c3d958ec649e10d4476744b6d4e423d90543f4b07c02f25994e21cc90f24c2c 5.12kB / 5.12kB                                                           0.0s
 => => sha256:af6eaf76a39c2d3e7e0b8a0420486e3df33c4027d696c076a99a3d0ac09026af 3.26MB / 3.26MB                                                           1.6s
 => => sha256:32de875b6464e47f0cdb1931e903b8083edc3da875f23c526c9642d286b61167 156B / 156B                                                               1.6s
 => => extracting sha256:af6eaf76a39c2d3e7e0b8a0420486e3df33c4027d696c076a99a3d0ac09026af                                                                0.1s
 => => extracting sha256:55522c79112429742fe76c795b9509c5cd1e8198e0caa2a1e355c0e60a719576                                                                0.0s
 => => extracting sha256:77c3719091df856c5f475ef1f915f5bdefae5a829c12d4ae75914e31c581935f                                                                1.2s
 => => extracting sha256:32de875b6464e47f0cdb1931e903b8083edc3da875f23c526c9642d286b61167                                                                0.0s
 => [2/7] RUN apk update                                                                                                                                 2.0s
 => [3/7] RUN apk upgrade                                                                                                                                0.5s
 => [4/7] RUN apk add git                                                                                                                                2.4s
 => [5/7] RUN apk add gettext                                                                                                                            3.1s
 => [6/7] RUN apk add make                                                                                                                               0.4s
 => [7/7] RUN go install github.com/itchyny/gojq/cmd/gojq@latest                                                                                         6.1s
 => exporting to image                                                                                                                                   0.2s
 => => exporting layers                                                                                                                                  0.2s
 => => writing image sha256:139809a253ef808a77cbc25937e3809da9eaa6415c5d8ffc3477ba18615a7bb0                                                             0.0s
```

**Comment by atyutyunnik** [comment] 2023-02-11 01:01
executed 
```docker system prune -a```

Same effect. But using a non-latest go cures (or works around) the issue, for example
```
echo "FROM golang:1.19.5-alpine3.17 as build
RUN apk update
RUN apk upgrade
RUN apk add git
RUN apk add gettext
RUN apk add make
ENV VERSION=latest
ENV CGO_ENABLED=0
RUN go install github.com/itchyny/gojq/cmd/gojq@latest" | docker build --platform linux/arm64 --build-arg TARGETARCH=arm64  -f - .
```

**Comment by itchyny** [comment] 2023-02-11 01:33
What happens when you specify `FROM --platform=$BUILDPLATFORM` at the first line?

**Comment by atyutyunnik** [comment] 2023-02-11 01:43
> What happens when you specify `FROM --platform=$BUILDPLATFORM` at the first line?

Forgot to mention I build using qemu on otherwise AMD64 platform. Here is the output:
```
$ echo "FROM --platform=$BUILDPLATFORM golang:alpine as build
RUN apk update
RUN apk upgrade
RUN apk add git
RUN apk add gettext
RUN apk add make
ENV VERSION=latest
ENV CGO_ENABLED=0
RUN go install github.com/itchyny/gojq/cmd/gojq@latest" | docker build --platform linux/arm64 --build-arg TARGETARCH=arm64  -f - .
Sending build context to Docker daemon  72.24kB
Step 1/9 : FROM --platform= golang:alpine as build
 ---> 7c3d958ec649
Step 2/9 : RUN apk update
 ---> Using cache
 ---> 0d69e5de8c62
Step 3/9 : RUN apk upgrade
 ---> Using cache
 ---> 2e7ca44c8095
Step 4/9 : RUN apk add git
 ---> Using cache
 ---> 54500574a2f2
Step 5/9 : RUN apk add gettext
 ---> Using cache
 ---> 6542f6fcb963
Step 6/9 : RUN apk add make
 ---> Using cache
 ---> 80b4176f977d
Step 7/9 : ENV VERSION=latest
 ---> Using cache
 ---> 4f9058dbf1da
Step 8/9 : ENV CGO_ENABLED=0
 ---> Using cache
 ---> 933958531dd5
Step 9/9 : RUN go install github.com/itchyny/gojq/cmd/gojq@latest
 ---> [Warning] The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in e0cf8ffa1dcd
go: downloading github.com/itchyny/gojq v0.12.11
go: downloading github.com/mattn/go-isatty v0.0.16
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/itchyny/timefmt-go v0.1.5
go: downloading golang.org/x/sys v0.2.0
go: downloading github.com/rivo/uniseg v0.2.0
runtime: copying /usr/local/go/src/runtime/tls_arm64.h to /tmp/go-build3306510322/b010/tls_GOARCH.h: write /tmp/go-build3306510322/b010/tls_GOARCH.h: copy_file_range: function not implemented
The command '/bin/sh -c go install github.com/itchyny/gojq/cmd/gojq@latest' returned a non-zero code: 1
```

**Comment by itchyny** [comment] 2023-02-11 02:45
Escape the dollar sign or use single quotes.

**Comment by itchyny** [comment] 2023-02-11 10:07
Any way, this doesn't look like the issue of this package, so closing. Quick search leads me [here](https://codeberg.org/forgejo/forgejo/issues/324).

**Closed by itchyny** 2023-02-11 10:07 UTC
